import 'package:flutter/material.dart';

class FlexConfig {
  final List<BoxShadow>? boxShadow, boxShadowHover, baseBoxShadow;

  final Color? backgroundColor,
      borderColor,
      hoverColor,
      hoverTextColor,
      baseTextColor,
      baseColor;

  final String? borderRadius, padding, margin, hoverBorderRadius;
  final String flexDirection, verticalAlignment, horizontalAlignment;

  final bool expanded;

  final double scale;
  final double? width,
      height,
      widthPercent,
      heightPercent,
      parentWidthPercent,
      parentHeightPercent,
      gap,
      paddingHorizontal,
      paddingVertical,
      paddingTop,
      paddingBottom,
      paddingLeft,
      paddingRight,
      borderEndLeftRadius,
      borderEndRightRadius,
      borderStartLeftRadius,
      borderStartRightRadius,
      marginHorizontal,
      marginVertical,
      marginTop,
      marginBottom,
      marginLeft,
      marginRight,
      hoverBorderRadiusStartLeft,
      hoverBorderRadiusStartRight,
      hoverBorderRadiusEndLeft,
      hoverBorderRadiusEndRight,
      borderWidth;

  final int? durationHover;

  const FlexConfig({
    this.flexDirection = 'column',
    this.verticalAlignment = 'start',
    this.horizontalAlignment = 'start',
    this.backgroundColor,
    this.gap,
    this.width,
    this.height,
    this.widthPercent,
    this.heightPercent,
    this.parentWidthPercent,
    this.parentHeightPercent,
    this.padding,
    this.paddingHorizontal,
    this.paddingVertical,
    this.paddingTop,
    this.paddingBottom,
    this.paddingLeft,
    this.paddingRight,
    this.borderRadius,
    this.borderEndLeftRadius,
    this.borderEndRightRadius,
    this.borderStartLeftRadius,
    this.borderStartRightRadius,
    this.margin,
    this.marginHorizontal,
    this.marginVertical,
    this.marginTop,
    this.marginBottom,
    this.marginLeft,
    this.marginRight,
    this.hoverColor,
    this.hoverTextColor,
    this.baseTextColor,
    this.baseColor,
    this.scale = 1.0,
    this.hoverBorderRadius,
    this.hoverBorderRadiusStartLeft,
    this.hoverBorderRadiusStartRight,
    this.hoverBorderRadiusEndLeft,
    this.hoverBorderRadiusEndRight,
    this.borderColor,
    this.borderWidth,
    this.expanded = false,
    this.boxShadow,
    this.boxShadowHover,
    this.baseBoxShadow,
    this.durationHover,
  });

  FlexConfig copyWith({
    List<BoxShadow>? boxShadow, boxShadowHover, baseBoxShadow,
    Color? backgroundColor,
      borderColor,
      hoverColor,
      hoverTextColor,
      baseTextColor,
      baseColor,
    String? borderRadius, padding, margin, hoverBorderRadius,
    String? flexDirection, verticalAlignment, horizontalAlignment,
    bool? expanded,
    double? scale,
    double? width,
      height,
      widthPercent,
      heightPercent,
      parentWidthPercent,
      parentHeightPercent,
      gap,
      paddingHorizontal,
      paddingVertical,
      paddingTop,
      paddingBottom,
      paddingLeft,
      paddingRight,
      borderEndLeftRadius,
      borderEndRightRadius,
      borderStartLeftRadius,
      borderStartRightRadius,
      marginHorizontal,
      marginVertical,
      marginTop,
      marginBottom,
      marginLeft,
      marginRight,
      hoverBorderRadiusStartLeft,
      hoverBorderRadiusStartRight,
      hoverBorderRadiusEndLeft,
      hoverBorderRadiusEndRight,
      borderWidth,
      int? durationHover

  })
  {
    return FlexConfig(
    flexDirection: flexDirection ?? this.flexDirection,
    verticalAlignment: verticalAlignment ?? this.verticalAlignment,
    horizontalAlignment: horizontalAlignment ?? this.horizontalAlignment,
    backgroundColor: backgroundColor ?? this.backgroundColor,
    gap: gap ?? this.gap,
    width: width ?? this.width,
    height: height ?? this.height,
    widthPercent: widthPercent ?? this.widthPercent,
    heightPercent: heightPercent ?? this.heightPercent,
    parentWidthPercent: parentWidthPercent ?? this.parentWidthPercent,
    parentHeightPercent: parentHeightPercent ?? this.parentHeightPercent,
    padding: padding ?? this.padding,
    paddingHorizontal: paddingHorizontal ?? this.paddingHorizontal,
    paddingVertical: paddingVertical ?? this.paddingVertical,
    paddingTop: paddingTop ?? this.paddingTop,
    paddingBottom: paddingBottom ?? this.paddingBottom,
    paddingLeft: paddingLeft ?? this.paddingLeft,
    paddingRight: paddingRight ?? this.paddingRight,
    borderRadius: borderRadius ?? this.borderRadius,
    borderEndLeftRadius: borderEndLeftRadius ?? this.borderEndLeftRadius,
    borderEndRightRadius: borderEndRightRadius ?? this.borderEndRightRadius,
    borderStartLeftRadius: borderStartLeftRadius ?? this.borderStartLeftRadius,
    borderStartRightRadius: borderStartRightRadius ?? this.borderStartRightRadius,
    margin: margin ?? this.margin,
    marginHorizontal: marginHorizontal ?? this.marginHorizontal,
    marginVertical: marginVertical ?? this.marginVertical,
    marginTop: marginTop ?? this.marginTop,
    marginBottom: marginBottom ?? this.marginBottom,
    marginLeft: marginLeft ?? this.marginLeft,
    marginRight: marginRight ?? this.marginRight,
    hoverColor: hoverColor ?? this.hoverColor,
    hoverTextColor: hoverTextColor ?? this.hoverTextColor,
    baseTextColor: baseTextColor ?? this.baseTextColor,
    baseColor: baseColor ?? this.baseColor,
    scale: scale ?? this.scale ,
    hoverBorderRadius: hoverBorderRadius ?? this.hoverBorderRadius,
    hoverBorderRadiusStartLeft: hoverBorderRadiusStartLeft ?? this.hoverBorderRadiusStartLeft,
    hoverBorderRadiusStartRight: hoverBorderRadiusStartRight ?? this.hoverBorderRadiusStartRight,
    hoverBorderRadiusEndLeft: hoverBorderRadiusEndLeft ?? this.hoverBorderRadiusEndLeft,
    hoverBorderRadiusEndRight: hoverBorderRadiusEndRight ?? this.hoverBorderRadiusEndRight,
    borderColor: borderColor ?? this.borderColor,
    borderWidth: borderWidth ?? this.borderWidth,
    expanded: expanded  ?? this.expanded ,
    boxShadow: boxShadow ?? this.boxShadow,
    boxShadowHover: boxShadowHover ?? this.boxShadowHover,
    baseBoxShadow: baseBoxShadow ?? this.baseBoxShadow,
    durationHover: durationHover ?? this.durationHover,
    );
  }
}

